### numpy를 다운로드

In [42]:
!pip install numpy

You should consider upgrading via the '/Users/kim_mintae/opt/anaconda3/bin/python -m pip install --upgrade pip' command.


### numpy를 임포트 한다!
### numpy as np , numpy를 np로 사용가능
numpy란? 파이썬에서 리스트형태를 좀더 활용성있게 만든것.

In [3]:
import numpy as np

## 기본 넘파일 배열 생성

In [5]:
#기본 넘파일 배열 생성
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


## List로 생성된 데이터를 numpy배열로 전환가능

In [6]:
data = [1,2,3,4,5]
data2 = [2,3,4,5,6]

np_data = np.array(data)
np_data2 = np.array(data2)
print("numpy화",np_data)

numpy화 [1 2 3 4 5]


## List + List

In [7]:
data3 = data + data2
print("List 더하기",data3)

List 더하기 [1, 2, 3, 4, 5, 2, 3, 4, 5, 6]


## numpy + numpy

In [8]:
np_data3 = np_data + np_data2
print("numpy 더하기",np_data3)
print("data의 형태",np_data.shape,np_data3.shape)

numpy 더하기 [ 3  5  7  9 11]
data의 형태 (5,) (5,)


## 사칙연산

In [9]:
np_data3 = np_data * np_data2
print("곱하기",np_data3)

np_data3 = np_data - np_data2
print("빼기",np_data3)

np_data3 = np_data / np_data2
print("나누기",np_data3)

곱하기 [ 2  6 12 20 30]
빼기 [-1 -1 -1 -1 -1]
나누기 [0.5        0.66666667 0.75       0.8        0.83333333]


## 크기가 다른 배열 연산 불가능

In [8]:
np_data4 = np.array([1,2,3,4])
print(np_data+np_data4)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [10]:
lista = [1,2,3,4,5]
list_2 = [[1,2],[3,4]]
print(list_2)
print(np.shape(list_2))

[[1, 2], [3, 4]]
(2, 2)


## 다차원 numpy배열 만들어보기

In [11]:
np_data  = np.array([[1,2],[3,4],[5,6]])
np_data2 = np.array([[3,4],[5,6],[7,8]])


np_data4 = np_data + np_data2
print("numpy 덧샘\n",np_data4)

np_data4 = np_data - np_data2
print("numpy 뺄샘\n",np_data4)

np_data4 = np_data * np_data2
print("numpy 곱샘\n",np_data4)

np_data4 = np_data / np_data2
print("numpy 나눗샘\n",np_data4)

numpy 덧샘
 [[ 4  6]
 [ 8 10]
 [12 14]]
numpy 뺄샘
 [[-2 -2]
 [-2 -2]
 [-2 -2]]
numpy 곱샘
 [[ 3  8]
 [15 24]
 [35 48]]
numpy 나눗샘
 [[0.33333333 0.5       ]
 [0.6        0.66666667]
 [0.71428571 0.75      ]]


## broad cast 기능
 이차원 배열에 일차원 배열을 더해줌 열이 크기가 같을 경우

In [ ]:
# 1 2 3
# 4 5 6
 1 2 3

In [43]:
np_data = np.array([[1,2,3],[4,5,6]])
np_data2 = np.array([1,2,3])

np_data3 = np_data + np_data2
print(np_data3)

np_data3 = np_data - np_data2
print(np_data3)

np_data3 = np_data * np_data2
print(np_data3)

np_data3 = np_data / np_data2
print(np_data3)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


## 그 외의 연산기능

In [44]:
np_data = np.array([[1,2,3],[4,5,6]])

np_data3 = np_data + 1
print(np_data3)

np_data3 = np_data - 1
print(np_data3)

np_data3 = np_data * 2
print(np_data3)

np_data3 = np_data / 2
print(np_data3)

np_data3 = np_data ** 2
print(np_data3)

[[2 3 4]
 [5 6 7]]
[[0 1 2]
 [3 4 5]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[ 1  4  9]
 [16 25 36]]


## 그외 numpy 생성 방법
, zeros
, arange
, ones
, random.randn

In [24]:
a = np.zeros(10)
print(a)
a = np.zeros((3,5))
print(a)

# ones
b = np.ones(9)
print(b)
b = np.ones((2,10))
print(b)

# arange
c = np.arange(10)
print(c)
c = np.arange(3,10)
print(c)

#랜덤 생성
rand = np.random.randn(8,4)
print("랜덤\n",rand)

#문자열
name = np.array(["민태","민태2","민태3"])
print("문자열\n",name)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]
랜덤
 [[ 0.86472596 -0.50242366 -0.94224425 -0.68636133]
 [ 0.30289271 -0.66338919 -2.15015039 -0.36085297]
 [ 1.00427974  0.47234275 -0.90068825 -0.99906302]
 [ 0.47201787  0.5583932  -2.10586123 -0.57678264]
 [ 1.08366392  1.41314645 -2.02386599  1.99338041]
 [ 0.04187303 -1.04676587 -1.59761291  0.10611916]
 [ 0.01732501 -0.44868045  0.16269204  0.23156254]
 [-3.01945981 -0.26823054  0.72243265 -0.77289324]]
문자열
 ['민태' '민태2' '민태3']


## linspace

In [18]:
x = np.linspace(0, 99, 100)
print(x)

x = np.linspace(0, 10, 11)


x = np.linspace(0, 20, 20)
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


## 차원 및 배열 형태 바꾸기
reshape

In [21]:
X = np.arange(9).reshape((3,3))
print(X)

X = np.arange(8).reshape((2,2,2))
print(X)

X = np.array([[3,5],[1,2]]).flatten()
print(X)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[3 5 1 2]


## 그 외의 연산 함수들

In [45]:
# 함수
a = np.array([[1,-2,3],[4,-5,6],[-7,-8,-9]])
# 절댓값
print(np.abs(a))
# 제곱근
print(np.sqrt(a))
# 제곱
print(np.square(a))
# e의 지수 로그
print(np.exp(a))
# 로그
print(np.log(a))
print(np.log10(a))
print(np.log2(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.                nan 1.73205081]
 [2.                nan 2.44948974]
 [       nan        nan        nan]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[2.71828183e+00 1.35335283e-01 2.00855369e+01]
 [5.45981500e+01 6.73794700e-03 4.03428793e+02]
 [9.11881966e-04 3.35462628e-04 1.23409804e-04]]
[[0.                nan 1.09861229]
 [1.38629436        nan 1.79175947]
 [       nan        nan        nan]]
[[0.                nan 0.47712125]
 [0.60205999        nan 0.77815125]
 [       nan        nan        nan]]
[[0.              nan 1.5849625]
 [2.              nan 2.5849625]
 [      nan       nan       nan]]


<ipython-input-45-ff042c502d43>:6: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(a))
<ipython-input-45-ff042c502d43>:12: RuntimeWarning: invalid value encountered in log
  print(np.log(a))
<ipython-input-45-ff042c502d43>:13: RuntimeWarning: invalid value encountered in log10
  print(np.log10(a))
<ipython-input-45-ff042c502d43>:14: RuntimeWarning: invalid value encountered in log2
  print(np.log2(a))


## 중간 문제1.  1~15까지의 숫자를 가진 3*5의 리스트를 만들어라!
## 중간 문제2.  문제1의 numpy에 제곱 연산을 하여라!
## 중간 문제3.  문제1를 linspace로 구현하여라!

In [29]:
a=np.arange(1,16).reshape((3,5))
print(a)
b = a  ** 2
print(b)
c = np.linspace(1,15,15).reshape((3,5))
print(c)

print(a.max())
print(a.min())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]
15
1


## 인덱싱

In [24]:
a = np.arange(10)

print(a)
print(a[0])
print(a[3])
print(a[3:9])

[0 1 2 3 4 5 6 7 8 9]
0
3
[3 4 5 6 7 8]


## 다차원 인덱싱

In [26]:
a = np.array([[1,2,3],[4,5,6]])
print(a[0,0])


print(a[:,1:2])

print(a[:,1])

print((a[0,1]))

1
[[2]
 [5]]
[2 5]
2


## 최댓갓 최솟값 누적값 출력 함수들

In [27]:
a = np.arange(8).reshape(2, 4)**2
print(a)
# [[ 0  1  4  9]
#  [16 25 36 49]]

# 모든 요소의 합
print(a.sum())
# 140

# 모든 요소 중 최소값
print(a.min())
# 0

# 모든 요소 중 최대값
print(a.max())
# 49

# 모든 요소 중 최대값의 인덱스
print(a.argmax())
# 7

# 모든 요소의 누적합
print(a.cumsum())

[[ 0  1  4  9]
 [16 25 36 49]]
140
0
49
7
[  0   1   5  14  30  55  91 140]


## 중간 문제4. 위 문제 1,3의 배열에서 최댓,최소값 을 출력하라!

## 마스크 연산

In [35]:
np_data = np.array([1,2,3,4,5,6])

mask1 = np_data == 1
print(mask1)

mask2 = np_data > 4
print(mask2)

a = np_data[mask1]
print(a)

b = np_data[mask2]
print(b)

[ True False False False False False]
[False False False False  True  True]
[1]
[5 6]


## 문자열의 마스크 연산

In [31]:
name = np.array(["김창성","윤성희","장혜진","백선욱","김환국"])


daniel = name == "김창성"
print(daniel)

c = name >= "이"
print(c)

print(name[c])
print(name[daniel])

[ True False False False False]
[False False  True False False]
['장혜진']
['김창성']


## 중간문제5. 랜덤한 수를 가지는 길이 100짜리의 배열을 만들어서 1보다 큰수만 출력하라.

In [40]:
rand = np.random.randn(100)
a = rand > 1 
print(rand[a])

100
[1.08581162 1.37528132 2.72717555 1.92926538 1.37167025 1.12427447
 1.89620981 1.32807512 1.01307889 2.02967724 1.43908411 1.80684538
 1.48837366 1.49602471 2.06718916 1.32020432 1.72231782 1.24242015
 1.57402946 1.80411999 1.31222695 2.30837579]


# pandas

In [43]:
!pip install pandas

You should consider upgrading via the '/Users/kim_mintae/opt/anaconda3/bin/python -m pip install --upgrade pip' command.


In [47]:
import pandas as pd

## 데이터 read하기 

In [48]:
data = pd.read_csv("train.csv")

In [55]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    0  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1   
2                               Heikkinen, Miss. Laina    1  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1   
4                             Allen, Mr. William Henry    0  35.0      0   
..                                                 ...  ...   ...    ...   
886                              Montvila, Rev. Juozas    0  27.0      0   
887                       Graham, Miss. Margaret Edith    1  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"    1   NaN      1   
889                              Behr, Mr. Karl Howell    0  26.0      0   
890                                Dooley, Mr. Patrick    0  32.0      0   

     Parch            Ticket     Fare  
0        0         A/5 21171   7.2500  
1        0          PC 17599  71.2833  
2        0  STON/O2. 3101282   7.9250  
3        0            113803  53.1000  
4        0            373450   8.0500  
..     ...               ...      ...  
886      0            211536  13.0000  
887      0            112053  30.0000  
888      2        W./C. 6607  23.4500  
889      0            111369  30.0000  
890      0            370376   7.7500  

[891 rows x 10 columns]

In [51]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
dtypes: float64(2), int64(5), object(3)
memory usage: 69.7+ KB


## 데이터 전처리
nan 값 결측치 제거 

In [7]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [50]:
data = data.drop(['Cabin','Embarked'],axis=1)

In [9]:
data["Age"].fillna(data.groupby("Sex")["Age"].transform("mean"), inplace=True)

In [54]:
sex_mapping = {"male": 0, "female": 1}
data['Sex'] = data['Sex'].map(sex_mapping)

## 마스크 연산

In [57]:
male_mask = data['Sex'] == 0
female_mask = data['Sex'] == 1

male = data[male_mask]
female = data[female_mask]

In [20]:
print(male['Age'].mean())
print(female['Age'].mean())

print(male['Age'].max())
print(female['Age'].min())

30.7266445916115
27.915708812260522
80.0
0.75


In [61]:
data["Survived"].value_counts()

0    549
1    342
Name: Survived, dtype: int64

## 중간문제6. 승객중 가장 나이가 많은 사람의 나이와 이름을 출력하라!
## 중간문제7. 살아남은 사람과 살아남지 못한 사람의 성비를 구하여라!
## 중간문제8. Pclass는 승차자의 등급을 의미한다. 각 등급간에 생존자수를 비교해보아라! (풀면 깊콘 드려요)

In [62]:
old_people = data["Age"] == data["Age"].max()
print(data[old_people]["Name"])

630    Barkworth, Mr. Algernon Henry Wilson
Name: Name, dtype: object


In [71]:
data[dead]

PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris   
4              5         0       3                  Allen, Mr. William Henry   
5              6         0       3                          Moran, Mr. James   
6              7         0       1                   McCarthy, Mr. Timothy J   
7              8         0       3            Palsson, Master. Gosta Leonard   
..           ...       ...     ...                                       ...   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

     Sex   Age  SibSp  Parch           Ticket     Fare  
0      0  22.0      1      0        A/5 21171   7.2500  
4      0  35.0      0      0           373450   8.0500  
5      0   NaN      0      0           330877   8.4583  
6      0  54.0      0      0            17463  51.8625  
7      0   2.0      3      1           349909  21.0750  
..   ...   ...    ...    ...              ...      ...  
884    0  25.0      0      0  SOTON/OQ 392076   7.0500  
885    1  39.0      0      5           382652  29.1250  
886    0  27.0      0      0           211536  13.0000  
888    1   NaN      1      2       W./C. 6607  23.4500  
890    0  32.0      0      0           370376   7.7500  

[549 rows x 10 columns]

In [63]:
dead = data["Survived"] == 0
survived = data["Survived"] == 1

print(data[dead]["Sex"].value_counts())
print(data[survived]["Sex"].value_counts())

0    468
1     81
Name: Sex, dtype: int64
1    233
0    109
Name: Sex, dtype: int64


In [64]:
class_1_mask = data["Pclass"] == 1
class_2_mask = data["Pclass"] == 2
class_3_mask = data["Pclass"] == 3

print(data[class_1_mask]["Survived"].value_counts())
print(data[class_2_mask]["Survived"].value_counts())
print(data[class_3_mask]["Survived"].value_counts())

1    136
0     80
Name: Survived, dtype: int64
0    97
1    87
Name: Survived, dtype: int64
0    372
1    119
Name: Survived, dtype: int64
